version: "2"

services:
  modeify:
    build:
      context: ./modeify
     # args:
     #   - SSH_KEY=/home/ubuntu/id_docker
    image: scvta/vta-modeify
    restart: always
    ports:
      - "80:80"
      - "443:443"

